arch:
    - amd64
    - ppc64le
language: node_js

node_js:
  - "stable"
  - "10"
  - "8"
  - "6.14"
  - "6.5"
  - "6.4"
  - "6.3"
  - "5.12"
  - "4.9"
  - "4.4"
  - "0.12"
#Excluding below versions since they are not supported by ppc64le    
jobs: 
  exclude:
    - node_js: "0.10"
      arch: ppc64le
